// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: memory_manager.proto

#include "memory_manager.pb.h"
#include "memory_manager.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace memorymanager {

static const char* MemoryManager_method_names[] = {
  "/memorymanager.MemoryManager/Create",
  "/memorymanager.MemoryManager/Set",
  "/memorymanager.MemoryManager/Get",
  "/memorymanager.MemoryManager/IncreaseRefCount",
  "/memorymanager.MemoryManager/DecreaseRefCount",
  "/memorymanager.MemoryManager/CreateNode",
  "/memorymanager.MemoryManager/GetNode",
  "/memorymanager.MemoryManager/UpdateNode",
};

std::unique_ptr< MemoryManager::Stub> MemoryManager::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MemoryManager::Stub> stub(new MemoryManager::Stub(channel, options));
  return stub;
}

MemoryManager::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Create_(MemoryManager_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Set_(MemoryManager_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(MemoryManager_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_IncreaseRefCount_(MemoryManager_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DecreaseRefCount_(MemoryManager_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateNode_(MemoryManager_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNode_(MemoryManager_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateNode_(MemoryManager_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MemoryManager::Stub::Create(::grpc::ClientContext* context, const ::memorymanager::CreateRequest& request, ::memorymanager::CreateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memorymanager::CreateRequest, ::memorymanager::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Create_, context, request, response);
}

void MemoryManager::Stub::async::Create(::grpc::ClientContext* context, const ::memorymanager::CreateRequest* request, ::memorymanager::CreateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memorymanager::CreateRequest, ::memorymanager::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, std::move(f));
}

void MemoryManager::Stub::async::Create(::grpc::ClientContext* context, const ::memorymanager::CreateRequest* request, ::memorymanager::CreateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::CreateResponse>* MemoryManager::Stub::PrepareAsyncCreateRaw(::grpc::ClientContext* context, const ::memorymanager::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memorymanager::CreateResponse, ::memorymanager::CreateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Create_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::CreateResponse>* MemoryManager::Stub::AsyncCreateRaw(::grpc::ClientContext* context, const ::memorymanager::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManager::Stub::Set(::grpc::ClientContext* context, const ::memorymanager::SetRequest& request, ::memorymanager::SetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memorymanager::SetRequest, ::memorymanager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void MemoryManager::Stub::async::Set(::grpc::ClientContext* context, const ::memorymanager::SetRequest* request, ::memorymanager::SetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memorymanager::SetRequest, ::memorymanager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void MemoryManager::Stub::async::Set(::grpc::ClientContext* context, const ::memorymanager::SetRequest* request, ::memorymanager::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::SetResponse>* MemoryManager::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::memorymanager::SetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memorymanager::SetResponse, ::memorymanager::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::SetResponse>* MemoryManager::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::memorymanager::SetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManager::Stub::Get(::grpc::ClientContext* context, const ::memorymanager::GetRequest& request, ::memorymanager::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memorymanager::GetRequest, ::memorymanager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void MemoryManager::Stub::async::Get(::grpc::ClientContext* context, const ::memorymanager::GetRequest* request, ::memorymanager::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memorymanager::GetRequest, ::memorymanager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void MemoryManager::Stub::async::Get(::grpc::ClientContext* context, const ::memorymanager::GetRequest* request, ::memorymanager::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::GetResponse>* MemoryManager::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::memorymanager::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memorymanager::GetResponse, ::memorymanager::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::GetResponse>* MemoryManager::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::memorymanager::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManager::Stub::IncreaseRefCount(::grpc::ClientContext* context, const ::memorymanager::IncreaseRefCountRequest& request, ::memorymanager::IncreaseRefCountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memorymanager::IncreaseRefCountRequest, ::memorymanager::IncreaseRefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_IncreaseRefCount_, context, request, response);
}

void MemoryManager::Stub::async::IncreaseRefCount(::grpc::ClientContext* context, const ::memorymanager::IncreaseRefCountRequest* request, ::memorymanager::IncreaseRefCountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memorymanager::IncreaseRefCountRequest, ::memorymanager::IncreaseRefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IncreaseRefCount_, context, request, response, std::move(f));
}

void MemoryManager::Stub::async::IncreaseRefCount(::grpc::ClientContext* context, const ::memorymanager::IncreaseRefCountRequest* request, ::memorymanager::IncreaseRefCountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IncreaseRefCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::IncreaseRefCountResponse>* MemoryManager::Stub::PrepareAsyncIncreaseRefCountRaw(::grpc::ClientContext* context, const ::memorymanager::IncreaseRefCountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memorymanager::IncreaseRefCountResponse, ::memorymanager::IncreaseRefCountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_IncreaseRefCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::IncreaseRefCountResponse>* MemoryManager::Stub::AsyncIncreaseRefCountRaw(::grpc::ClientContext* context, const ::memorymanager::IncreaseRefCountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIncreaseRefCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManager::Stub::DecreaseRefCount(::grpc::ClientContext* context, const ::memorymanager::DecreaseRefCountRequest& request, ::memorymanager::DecreaseRefCountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memorymanager::DecreaseRefCountRequest, ::memorymanager::DecreaseRefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DecreaseRefCount_, context, request, response);
}

void MemoryManager::Stub::async::DecreaseRefCount(::grpc::ClientContext* context, const ::memorymanager::DecreaseRefCountRequest* request, ::memorymanager::DecreaseRefCountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memorymanager::DecreaseRefCountRequest, ::memorymanager::DecreaseRefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DecreaseRefCount_, context, request, response, std::move(f));
}

void MemoryManager::Stub::async::DecreaseRefCount(::grpc::ClientContext* context, const ::memorymanager::DecreaseRefCountRequest* request, ::memorymanager::DecreaseRefCountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DecreaseRefCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::DecreaseRefCountResponse>* MemoryManager::Stub::PrepareAsyncDecreaseRefCountRaw(::grpc::ClientContext* context, const ::memorymanager::DecreaseRefCountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memorymanager::DecreaseRefCountResponse, ::memorymanager::DecreaseRefCountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DecreaseRefCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::DecreaseRefCountResponse>* MemoryManager::Stub::AsyncDecreaseRefCountRaw(::grpc::ClientContext* context, const ::memorymanager::DecreaseRefCountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDecreaseRefCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManager::Stub::CreateNode(::grpc::ClientContext* context, const ::memorymanager::CreateNodeRequest& request, ::memorymanager::CreateNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memorymanager::CreateNodeRequest, ::memorymanager::CreateNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateNode_, context, request, response);
}

void MemoryManager::Stub::async::CreateNode(::grpc::ClientContext* context, const ::memorymanager::CreateNodeRequest* request, ::memorymanager::CreateNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memorymanager::CreateNodeRequest, ::memorymanager::CreateNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateNode_, context, request, response, std::move(f));
}

void MemoryManager::Stub::async::CreateNode(::grpc::ClientContext* context, const ::memorymanager::CreateNodeRequest* request, ::memorymanager::CreateNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::CreateNodeResponse>* MemoryManager::Stub::PrepareAsyncCreateNodeRaw(::grpc::ClientContext* context, const ::memorymanager::CreateNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memorymanager::CreateNodeResponse, ::memorymanager::CreateNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::CreateNodeResponse>* MemoryManager::Stub::AsyncCreateNodeRaw(::grpc::ClientContext* context, const ::memorymanager::CreateNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManager::Stub::GetNode(::grpc::ClientContext* context, const ::memorymanager::GetNodeRequest& request, ::memorymanager::GetNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memorymanager::GetNodeRequest, ::memorymanager::GetNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNode_, context, request, response);
}

void MemoryManager::Stub::async::GetNode(::grpc::ClientContext* context, const ::memorymanager::GetNodeRequest* request, ::memorymanager::GetNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memorymanager::GetNodeRequest, ::memorymanager::GetNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNode_, context, request, response, std::move(f));
}

void MemoryManager::Stub::async::GetNode(::grpc::ClientContext* context, const ::memorymanager::GetNodeRequest* request, ::memorymanager::GetNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::GetNodeResponse>* MemoryManager::Stub::PrepareAsyncGetNodeRaw(::grpc::ClientContext* context, const ::memorymanager::GetNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memorymanager::GetNodeResponse, ::memorymanager::GetNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::GetNodeResponse>* MemoryManager::Stub::AsyncGetNodeRaw(::grpc::ClientContext* context, const ::memorymanager::GetNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryManager::Stub::UpdateNode(::grpc::ClientContext* context, const ::memorymanager::UpdateNodeRequest& request, ::memorymanager::UpdateNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memorymanager::UpdateNodeRequest, ::memorymanager::UpdateNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateNode_, context, request, response);
}

void MemoryManager::Stub::async::UpdateNode(::grpc::ClientContext* context, const ::memorymanager::UpdateNodeRequest* request, ::memorymanager::UpdateNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memorymanager::UpdateNodeRequest, ::memorymanager::UpdateNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateNode_, context, request, response, std::move(f));
}

void MemoryManager::Stub::async::UpdateNode(::grpc::ClientContext* context, const ::memorymanager::UpdateNodeRequest* request, ::memorymanager::UpdateNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::UpdateNodeResponse>* MemoryManager::Stub::PrepareAsyncUpdateNodeRaw(::grpc::ClientContext* context, const ::memorymanager::UpdateNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memorymanager::UpdateNodeResponse, ::memorymanager::UpdateNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memorymanager::UpdateNodeResponse>* MemoryManager::Stub::AsyncUpdateNodeRaw(::grpc::ClientContext* context, const ::memorymanager::UpdateNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

MemoryManager::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManager_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManager::Service, ::memorymanager::CreateRequest, ::memorymanager::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memorymanager::CreateRequest* req,
             ::memorymanager::CreateResponse* resp) {
               return service->Create(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManager_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManager::Service, ::memorymanager::SetRequest, ::memorymanager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memorymanager::SetRequest* req,
             ::memorymanager::SetResponse* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManager_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManager::Service, ::memorymanager::GetRequest, ::memorymanager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memorymanager::GetRequest* req,
             ::memorymanager::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManager_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManager::Service, ::memorymanager::IncreaseRefCountRequest, ::memorymanager::IncreaseRefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memorymanager::IncreaseRefCountRequest* req,
             ::memorymanager::IncreaseRefCountResponse* resp) {
               return service->IncreaseRefCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManager_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManager::Service, ::memorymanager::DecreaseRefCountRequest, ::memorymanager::DecreaseRefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memorymanager::DecreaseRefCountRequest* req,
             ::memorymanager::DecreaseRefCountResponse* resp) {
               return service->DecreaseRefCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManager_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManager::Service, ::memorymanager::CreateNodeRequest, ::memorymanager::CreateNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memorymanager::CreateNodeRequest* req,
             ::memorymanager::CreateNodeResponse* resp) {
               return service->CreateNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManager_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManager::Service, ::memorymanager::GetNodeRequest, ::memorymanager::GetNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memorymanager::GetNodeRequest* req,
             ::memorymanager::GetNodeResponse* resp) {
               return service->GetNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryManager_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryManager::Service, ::memorymanager::UpdateNodeRequest, ::memorymanager::UpdateNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memorymanager::UpdateNodeRequest* req,
             ::memorymanager::UpdateNodeResponse* resp) {
               return service->UpdateNode(ctx, req, resp);
             }, this)));
}

MemoryManager::Service::~Service() {
}

::grpc::Status MemoryManager::Service::Create(::grpc::ServerContext* context, const ::memorymanager::CreateRequest* request, ::memorymanager::CreateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManager::Service::Set(::grpc::ServerContext* context, const ::memorymanager::SetRequest* request, ::memorymanager::SetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManager::Service::Get(::grpc::ServerContext* context, const ::memorymanager::GetRequest* request, ::memorymanager::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManager::Service::IncreaseRefCount(::grpc::ServerContext* context, const ::memorymanager::IncreaseRefCountRequest* request, ::memorymanager::IncreaseRefCountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManager::Service::DecreaseRefCount(::grpc::ServerContext* context, const ::memorymanager::DecreaseRefCountRequest* request, ::memorymanager::DecreaseRefCountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManager::Service::CreateNode(::grpc::ServerContext* context, const ::memorymanager::CreateNodeRequest* request, ::memorymanager::CreateNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManager::Service::GetNode(::grpc::ServerContext* context, const ::memorymanager::GetNodeRequest* request, ::memorymanager::GetNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryManager::Service::UpdateNode(::grpc::ServerContext* context, const ::memorymanager::UpdateNodeRequest* request, ::memorymanager::UpdateNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace memorymanager

